version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    env_file:
      - .env  # Ensure you have a .env file containing MONGO_URI
